"apiVersion": "networking.k8s.io/v1"
"kind": "IngressClass"
"metadata":
  "annotations":
    "ingressclass.kubernetes.io/is-default-class": "true"
  "labels":
    "component": "networking"
    "managed-by": "terraform"
    "project": "chat-app"
    "security.company": "chat-app"
    "security.environment": "dev"
    "security.managed-by": "terraform"
    "security.version": "1.0.0"
    "terraform": "true"
  "name": "nginx"
"spec":
  "controller": "k8s.io/ingress-nginx"
