"apiVersion": "v1"
"data":
  "config": |
    "address_pools":
    - "addresses":
      - "172.18.255.200-172.18.255.250"
      "name": "default"
      "protocol": "layer2"
"kind": "ConfigMap"
"metadata":
  "labels":
    "component": "networking"
    "managed-by": "terraform"
    "project": "chat-app"
    "security.company": "chat-app"
    "security.environment": "dev"
    "security.managed-by": "terraform"
    "security.version": "1.0.0"
    "terraform": "true"
  "name": "metallb-config"
  "namespace": "metallb-system"
