apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-config
  namespace: argocd
  labels:
    app.kubernetes.io/component: infrastructure
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/dmitri166/ghost_on_prem_project
    targetRevision: master
    path: platform/manifests/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false  # Monitoring namespace already exists from Helm
  revisionHistoryLimit: 10
