apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.primary.persistence.size }}
  storageClassName: {{ .Values.primary.persistence.storageClass | default "" }}
