apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "common.names.fullname" . }}
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc }}
  mysql-password: {{ .Values.auth.password | b64enc }}
