"apiVersion": "policy/v1beta1"
"kind": "PodSecurityPolicy"
"metadata":
  "labels":
    "component": "security"
    "managed-by": "terraform"
    "project": "chat-app"
    "security.company": "chat-app"
    "security.environment": "dev"
    "security.managed-by": "terraform"
    "security.version": "1.0.0"
    "terraform": "true"
  "name": "restricted"
"spec":
  "allowPrivilegeEscalation": false
  "fsGroup":
    "rule": "RunAsAny"
  "privileged": false
  "requiredDropCapabilities":
  - "ALL"
  "runAsUser":
    "rule": "MustRunAsNonRoot"
  "seLinux":
    "rule": "RunAsAny"
  "volumes":
    "configMap":
      "allowed": true
    "downwardAPI":
      "allowed": true
    "emptyDir":
      "allowed": true
    "persistentVolumeClaim":
      "allowed": true
    "projected":
      "allowed": true
    "secret":
      "allowed": true
